---
  - name: Set Jenkins IP as a fact
    set_fact:
      jenkins_ip: "{{ ansible_host }}"

  - name: Install Docker
    apt:
      name: docker.io
      state: present

   
  - name: Create /var/jenkins_home
    file:
      name: /var/jenkins_home
      state: directory
      mode: '0755'

  - name: Add NFS export to fstab file
    ansible.builtin.lineinfile:
      path: /etc/fstab
      line: "{{ nfs_ip }}:/{{ export_directory }} /var/jenkins_home nfs defaults 0 0"
      create: yes

  - name: Apply mounts
    shell: systemctl daemon-reload && mount -a

  - name: Set directory Permissions
    shell: chown -R 1000:1000 /var/jenkins_home

  
  - name: Create directory for docker build
    file:
      path: /docker
      state: directory
      mode: '0755'

  - name: Copy docker file for container orchestration
    copy:
      src: ./Dockerfile
      dest: /docker 
      mode: '0755'
  
  - name: Copy the plugins file for container orchestration
    copy:
      src: ./plugins.txt
      dest: /docker
      mode: '0755' 
  
  - name: Copy the casc file for container orchestration
    copy:
      src: ./casc.yaml
      dest: /docker
      mode: '0755'

  - name: Build the custom Jenkins Docker image
    community.docker.docker_image:
      name: custom-jenkins
      tag: latest
      build:
        path: /docker
      state: present

  - name: Start Jenkins container
    community.docker.docker_container:
      name: jenkins
      image: custom-jenkins
      state: started
      ports:
        - "8080:8080"
      volumes:
        - "/var/jenkins_home:/var/jenkins_home"
      restart_policy: unless-stopped

  