---
  - name: Set Jenkins IP as a fact
    set_fact:
      jenkins_ip: "{{ ansible_host }}"

  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Install Docker Compose
    apt:
      name: docker-compose
      state: present
  
  - name: Create /var/jenkins_home
    file:
      name: /var/jenkins_home
      state: directory

  - name: Add NFS export to fstab file
    ansible.builtin.lineinfile:
      path: /etc/fstab
      line: "{{ nfs_ip }}:/{{ export_directory }} /var/jenkins_home nfs defaults 0 0"
      create: yes

  - name: Apply mounts
    shell: systemctl daemon-reload && mount -a

  - name: Set directory Permissions
    shell: chown -R 1000:1000 /var/jenkins_home


  - name: Create directory for casc file
    file:
      path: /var/jenkins_home/casc_configs
      state: directory

  - name: Copy casc file for admin user creation and plugins installation
    copy:
      src: ./casc.yaml
      dest: /var/jenkins_home/casc_configs/casc.yaml

  - name: Create directory for docker compose
    file:
      path: /opt/jenkins
      state: directory
      mode: '0755'

  - name: Copy docker-compose file for container orchestration
    copy:
      src: ./docker-compose.yml
      dest: /opt/jenkins 

  - name: Start Jenkins container with Docker Compose
    command: docker-compose up -d
    args:
      chdir: /opt/jenkins

  