jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
    
  securityConfiguration:
    globalJobDslSecurityConfiguration:
      useScriptSecurity: true
    
  nodes:
  - permanent:
      name: "docker-agent"
      labelString: "docker"
      numExecutors: 2
      remoteFS: "/home/jenkins"
      launcher:
        jnlp:
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"

  - permanent:
      name: "ansible-agent"
      labelString: "ansible"
      numExecutors: 2
      remoteFS: "/home/jenkins"
      launcher:
        jnlp:
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"

  security:
    globalJobDslSecurityConfiguration:
      useScriptSecurity: true
    queueItemAuthenticator:
      authenticators:
        - global:
            strategy: triggeringUsersAuthorizationStrategy
