jenkins:
  securityRealm:
    local:
      users:
        - username: "admin"
          password: "adminpassword"
          fullName: "Administrator"
          email: "admin@example.com"
          roles:
            - "admin"

  authorizationStrategy:
    loggedInUsersCanDoAnything: true
    allowAnonymousRead: false

  nodes:
    - permanent:
        name: "docker-agent"
        description: "Node for Docker operations"
        remoteFS: "/home/jenkins/docker"
        labels: "docker"
        usageMode: EXCLUSIVE
        retentionStrategy: "always"
        launchMethod:
          ssh:
            host: "docker-node.example.com"
            port: 22
            credentialsId: "docker-ssh-credentials"
    - permanent:
        name: "ansible-agent"
        description: "Node for Ansible operations"
        remoteFS: "/home/jenkins/ansible"
        labels: "ansible"
        usageMode: EXCLUSIVE
        retentionStrategy: "always"
        launchMethod:
          ssh:
            host: "ansible-node.example.com"
            port: 22
            credentialsId: "ansible-ssh-credentials"

  tools:
    docker:
      installations:
        - name: "docker"
          dockerHost: "unix:///var/run/docker.sock"
    ansible:
      installations:
        - name: "ansible"
          home: "/usr/local/bin/ansible"